### ISSUE TITLE
Discover more page image not hiding

### ISSUE THREAD

**Issue by giuliobosco** [itflow-xyz/itflow-xyz.github.io#1]
The image on the main page do not hides

![Screenshot 2022-09-28 at 09 08 26](https://user-images.githubusercontent.com/16956636/192712377-dcee3200-fc6a-4f11-8698-ee1cea2c4137.png)

**Comment by Estesq** [comment]
I am not able to see this error in my Windows system, I tried all available browsers. Please find the attached video for an explanation.
Please confirm in which browser you are getting this error.


https://user-images.githubusercontent.com/85756312/192721974-d8035049-98ce-485e-a8d2-500e653d2b20.mp4

**Comment by giuliobosco** [comment]
@Estesq did you pulled last commits?
