### ISSUE TITLE
integrate cookies

### ISSUE THREAD

**Issue by giuliobosco** [itflow-xyz/itflow-xyz.github.io#17]

**Comment by Estesq** [comment]
Do you want me to add Consent window saying "allow cookies"?


![Screenshot_2022-09-29-20-21-30-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/85756312/193064978-e9e9600c-271a-4c15-83ef-c97608de969c.jpg)

**Comment by giuliobosco** [comment]
@Estesq can not see enything!

**Comment by Estesq** [comment]
Please try again and this time open it in incognito.

**Comment by giuliobosco** [comment]
@Estesq, did not worked.

<img width="1440" alt="Screenshot 2022-10-03 at 08 23 16" src="https://user-images.githubusercontent.com/16956636/193513209-a3053003-ccdd-48a6-853a-9e0dbecf0d65.png">
