### ISSUE TITLE
[BUG] mobile - navbar - fix padding

### ISSUE THREAD

**Issue by giuliobosco** [itflow-xyz/itflow-xyz.github.io#5]
when scrolling in mobile the size of the logo in the navbar is reduced, should be reduced also the `padding-top` and `padding-bottom`.

**Comment by giuliobosco** [comment]
@Estesq the padding should be reduced only while scrolling, as animation.

**Comment by Estesq** [comment]
Do you want me to enlarge the logo again as we stop scrolling?

**Comment by giuliobosco** [comment]
@Estesq no
